#ifndef ORACLE_DB_CONFIG_H
#define ORACLE_DB_CONFIG_H

#define ORACLE_ENV_USER "ORACLE_USER"
#define ORACLE_ENV_PASSWORD "ORACLE_PASSWORD"
#define ORACLE_ENV_CONNECT_STRING "ORACLE_CONNECT_STRING"

#define ORACLE_USER_MAX_LEN 64
#define ORACLE_PASSWORD_MAX_LEN 64
#define ORACLE_CONNECT_STRING_MAX_LEN 128

#define ORACLE_DEFAULT_CONNECT_STRING "localhost:1521/XEPDB1"

#endif
